version: '3'
services:
  blog_app:
    container_name: nest_backend
    build: .
    ports:
      - 8000:3000
    depends_on:
      - postgres
    volumes:
      - webapp:/var/lib/data
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=blog
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data
volumes:
  postgre:
    driver: local
  webapp:
    driver: local
